version: '3.4'

services:
  scorecard-cbt:
    image: ${DOCKER_REGISTRY-}scorecardcbt
    build:
      context: .
      dockerfile: scorecard-cbt/Dockerfile
    ports:
      - "5445:80"
  postgresql_database:
    image: postgres
    environment:
       - POSTGRES_USER=postgres
       - POSTGRES_PASSWORD=12345
       - POSTGRES_DB=CBTDb
    ports:
       - "5432:5432"
    restart: unless-stopped
    volumes:
       - database-data:/var/lib/postgresql/data/
  pgadmin:
    image: dpage/pgadmin4
    environment:
        PGADMIN_DEFAULT_EMAIL: pgadmin4@pgadmin.org
        PGADMIN_DEFAULT_PASSWORD: admin
    ports:
       - "5050:80"
    restart: always
    volumes:
       - pgadmin:/root/.pgadmin/

volumes:
  database-data:
  pgadmin: